image: "node:alpine"

stages:
  - build

build:
  stage: build
  script:
    - cd client
    - yarn install --production
    - yarn codegen:config --api-id $API_ID --api-key $API_KEY --api-url $API_URL --auth-mode API_KEY --region eu-central-1 --bucket-name $BUCKET_NAME
    - yarn build
  artifacts:
    paths:
      - ./client/build
